### ISSUE TITLE
Enable logs in staging

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma_reports#23]
There are no Rails logs in staging and that is very annoying. AFAIK that is something Rails does by default.

**Comment by lastgabs** [comment]
Hey, I can work on this for you.

Is your production environment currently logging? Are you using heroku as a host?

**Comment by sauloperez** [comment]
Hi @lastgabs, thanks a lot! We host the app in https://www.scaleway.com/.

I checked again though and the `log/staging.log` is there :astonished:. The logs however, both in staging and production, do not show all the information we'd like so now it must be related to the log level.

Sorry for the inconvenience. If you are still eager to help, you can take a look at https://github.com/coopdevs/katuma_reports/issues/17 for instance.
